packages:
  - .

pnpm:
  autoInstallPeers: true
  strictPeerDependencies: false
  overrides:
    postcss: ^8.5.10
    cookie: ^0.7.0
  allowBuilds:
    sharp: true
    unrs-resolver: true
  packageImportMethod: clone-or-copy
